{{- if .Values.cloudflare.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "cloudflare-ddns" .Values.cloudflare.secretName }}
type: Opaque
stringData:
  {{ default "apiToken" .Values.cloudflare.secretKey }}: {{ required "cloudflare.apiToken is required when cloudflare.enabled=true" .Values.cloudflare.apiToken | quote }}
{{- end }}
